/*
 * Public API Surface of @venntier/design-system
 *
 * Venntier Design System v3 - Angular 19 + Material Design 3
 * OpenAI-inspired minimalist design with monochromatic interaction states
 */

// Service exports
export * from './lib/services/theme.service';

// Type exports
export type VenntierTheme = 'light' | 'dark';

// Constants
export const VENNTIER_THEME_CONFIG = {
  defaultTheme: 'light' as const,
  storageKey: 'vt-theme-preference',
  cssVariablePrefix: 'mat-sys',
  themes: {
    light: 'vt-theme-light',
    dark: 'vt-theme-dark',
  },
} as const;

// MD3 COMPLIANT: Design tokens access (for runtime usage)
// These reference the auto-generated --mat-sys-* tokens from Angular Material
export const VENNTIER_TOKENS = {
  colors: {
    // Standard MD3 color tokens (auto-generated by Angular Material)
    primary: 'var(--mat-sys-primary)',
    secondary: 'var(--mat-sys-secondary)',
    tertiary: 'var(--mat-sys-tertiary)',
    surface: 'var(--mat-sys-surface)',
    background: 'var(--mat-sys-background)',
    error: 'var(--mat-sys-error)',

    // Custom extension tokens (defined in our design system)
    hover: 'var(--mat-sys-hover)',
    selected: 'var(--mat-sys-selected)',
    focusRing: 'var(--mat-sys-focus-ring)',
    dataPrimary: 'var(--mat-sys-data-primary)',

    // Semantic color tokens
    onPrimary: 'var(--mat-sys-on-primary)',
    onSecondary: 'var(--mat-sys-on-secondary)',
    onTertiary: 'var(--mat-sys-on-tertiary)',
    onSurface: 'var(--mat-sys-on-surface)',
    onBackground: 'var(--mat-sys-on-background)',
    onError: 'var(--mat-sys-on-error)',

    // Outline tokens
    outline: 'var(--mat-sys-outline)',
    outlineVariant: 'var(--mat-sys-outline-variant)',
  },
  spacing: {
    xs: 'var(--mat-sys-spacing-4)',
    sm: 'var(--mat-sys-spacing-8)',
    md: 'var(--mat-sys-spacing-16)',
    lg: 'var(--mat-sys-spacing-24)',
    xl: 'var(--mat-sys-spacing-32)',
  },
  shape: {
    sm: 'var(--mat-sys-shape-corner-small)',
    md: 'var(--mat-sys-shape-corner-medium)',
    lg: 'var(--mat-sys-shape-corner-large)',
    full: 'var(--mat-sys-shape-corner-full)',
  },
  motion: {
    short: 'var(--mat-sys-motion-duration-short)',
    medium: 'var(--mat-sys-motion-duration-medium2)',
    standard: 'var(--mat-sys-motion-easing-standard)',
    hover: 'var(--mat-sys-motion-hover)',
  },
} as const;

/*
 * SCSS Theme Usage
 *
 * Import the theme in your styles.scss:
 * @use '@venntier/design-system/theme' as vt-theme;
 *
 * Or import tokens directly:
 * @use '@venntier/design-system/tokens' as vt-tokens;
 *
 * Access design tokens:
 * .my-component {
 *   color: vt-tokens.color('primary');
 *   padding: vt-tokens.spacing(4);
 *   border-radius: vt-tokens.shape('medium');
 * }
 */
